name: Atualização automática do manifest.json

on: 
  push:
    branches: [ workflow_tests ]
    
    paths:
      - '**'
      - '!manifest.json'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Gerar manifest
      run: node generate-manifest.js

    - name: Fazer commit e push do manifest.json atualizado
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add manifest.json
        git diff --staged --quiet || git commit -m "Atualiza manifest.json automático"
        git push